name: PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.x'
        cache: 'yarn'

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install dependencies
      run: yarn install

    - name: Create binary directories
      run: |
        mkdir -p src-tauri/bin/post-rs
        mkdir -p src-tauri/bin/postcli

    - name: Download post-rs binaries
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/spacemeshos/post-rs/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')
        curl -L -o profiler.zip "https://github.com/spacemeshos/post-rs/releases/download/${LATEST_VERSION}/profiler-linux-${LATEST_VERSION}.zip"
        unzip profiler.zip -d src-tauri/bin/post-rs
        rm profiler.zip

    - name: Download postcli binaries
      run: |
        curl -L -o postcli.zip "https://github.com/spacemeshos/post/releases/latest/download/postcli-Linux.zip"
        unzip postcli.zip -d src-tauri/bin/postcli
        rm postcli.zip

    - name: Run tests
      run: yarn test

    - name: Build
      run: yarn build
